#!/usr/bin/env bash

#
# Strip libraries and binaries
#

TOOLS=`pwd`/out

source adjustEnvVars.sh || exit $?

$TARGET-strip --strip-debug    $TOOLS/{,$TARGET}/lib/* >> /dev/null
$TARGET-strip --strip-unneeded $TOOLS/{,$TARGET}/bin/* >> /dev/null

rm -rf $TOOLS/{,share}/{info,man,doc}


echo -e "${GRN}Successfully built a $TARGET cross-toolchain${CLR}"

#
# Delete extra files to free space
#
rm -rf deps
rm -rf obj

#
# Create zip
#
echo "Zipping"

zip -r -qdgds 50m out ./out || exit $?

echo "Size of out.zip: "
ls -sh out.zip

#
# Upload to gh-pages
#
echo "preparing to upload"
mkdir upload
( cd upload
 echo "git init and config"
 echo "copying zip file"
 cp ../out.zip ./out.zip
 cd ..
 npm install
 node upload.js
 )
