#!/usr/bin/env bash

#
# Strip libraries and binaries
#

TOOLS=`pwd`/out

source scripts/adjustEnvVars.sh || exit $?

$TARGET-strip --strip-debug    $TOOLS/{,$TARGET}/lib/* >> /dev/null
$TARGET-strip --strip-unneeded $TOOLS/{,$TARGET}/bin/* >> /dev/null

rm -rf $TOOLS/{,share}/{info,man,doc}


echo -e "${GRN}Successfully built a $TARGET cross-toolchain${CLR}"


#
# Create zip
#

zip -r out /out


