#!/usr/bin/env bash

#
# Strip libraries and binaries
#

TOOLS=`pwd`/out

source adjustEnvVars.sh || exit $?

$TARGET-strip --strip-debug    $TOOLS/{,$TARGET}/lib/* >> /dev/null
$TARGET-strip --strip-unneeded $TOOLS/{,$TARGET}/bin/* >> /dev/null

rm -rf $TOOLS/{,share}/{info,man,doc}


echo -e "${GRN}Successfully built a $TARGET cross-toolchain${CLR}"

#
# Delete extra files to free space
#
rm -rf deps
rm -rf obj

#
# Create zip
#
echo "Zipping"

zip -r -qdgds 50m out ./out || exit $?

echo "Size of out.zip: "
ls -sh out.zip

#
# Upload to gh-pages
#
echo "preparing to upload"
mkdir upload
( cd upload
 echo "git init and config"
 git init
 git config user.name "Travis-CI"
 git config user.email "travis@node-os.com"
 echo "copying zip file"
 cp ../out.zip ./out.zip
 echo "adding file"
 git add .
 echo "git commit"
 git commit -m "Upload to GHPages"
 echo "git push"
 git push --force --quiet "https://${secret}@${GH_REF}" master:gh-pages > /dev/null 2>&1
)
